// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuSjyxfvxz-Vv9vXpyKP51WPiYhPZ7HmA',
    appId: '1:606914451469:web:9b148801f3ffa709d8dd44',
    messagingSenderId: '606914451469',
    projectId: 'autoave-global',
    authDomain: 'autoave-global.firebaseapp.com',
    storageBucket: 'autoave-global.appspot.com',
    measurementId: 'G-TLCFT4NY3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4s5qQirdCwk8ehEL_A1gTU-NAW6L9SYw',
    appId: '1:606914451469:android:4af042d6d22c64ead8dd44',
    messagingSenderId: '606914451469',
    projectId: 'autoave-global',
    storageBucket: 'autoave-global.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfOLMyEEnuMg-RvhMdFu7FFhuL0gx7z0',
    appId: '1:606914451469:ios:cfbb3b003617ca90d8dd44',
    messagingSenderId: '606914451469',
    projectId: 'autoave-global',
    storageBucket: 'autoave-global.appspot.com',
    iosClientId: '606914451469-amm8t23b02aur77qk1ktcnkmtgdcspu0.apps.googleusercontent.com',
    iosBundleId: 'in.autoave.app',
  );
}
